#!/bin/bash

./clean

echo " "
echo " ==== COMPUTING 1-DIMENSIONAL FLAME ==== "
echo " "

# ==> Define input parameters
p_0=101325.0             # [Pa]
T_0=300.0                # [K]
T_plate=300.0            # [K]
U_in=0.2                 # [m/s]

# phi = 0.7 T = 300K
Yc_u=0.0                    # [-]
Yc_b=2.444368462162917e-03  # [-]
ht=-1.805951297124500e+05   # [J/kg]

nProcs=4            # [-]
simtime=0.1         # [s]
simtimestep=1.0e-5  # [s]
simwritesteps=100   # [-]

simwritetime=$(echo $simtime $simwritesteps | awk '{printf ($1/$2) }' )

# Copy FGM table
[ -f ${PWD}/constant/lookUp/database.fgm ] && rm ${PWD}/constant/lookUp/database.fgm
[ ! -f ${PWD}/constant/lookUp/database.fgm ] && cp ../../tables/database.fgm constant/lookUp/

# Copy 0 folder
[ -d ${PWD}/0/ ] && rm -rf ${PWD}/0/
[ ! -d ${PWD}/0/ ] && cp -r 0.orig/ 0/

# Copy system folder
[ -d ${PWD}/system/ ] && rm -rf ${PWD}/system/
[ ! -d ${PWD}/system/ ] && cp -r system.orig/ system/

# ---------- Set simulation settings ----------
sed -i "s/SIMULATIONTIME/$simtime/" system/controlDict
sed -i "s/SIMULATIONDELTATIME/$simtimestep/" system/controlDict
sed -i "s/SIMULATIONWRITETIME/${simwritetime}/" system/controlDict

sed -i "s/NPROCS/${nProcs}/" system/decomposeParDict

sed -i "s/INITIALPRESSURE/${p_0}/" 0/p
sed -i "s/INLETTEMPERATURE/${T_0}/" 0/T
sed -i "s/PLATETEMPERATURE/${T_plate}/" 0/T
sed -i "s/INLETVELOCITY/${U_in}/" 0/U
sed -i "s/INITIALPROGRESSVARIABLE/${Yc_u}/" 0/Yc
sed -i "s/INITIALENTHALPY/${ht}/" 0/ht
  
sed -i "s/INITIALPROGRESSVARIABLE/${Yc_u}/" system/setFieldsDict
sed -i "s/FINALPROGRESSVARIABLE/${Yc_b}/" system/setFieldsDict

# ---------- Run simulation ----------
[ -d ${PWD}/constant/polyMesh ] && rm -rf ${PWD}/constant/polyMesh
[ -f ${PWD}/log.blockMesh ] && rm ${PWD}/log.blockMesh
blockMesh > log.blockMesh
    
[ -f ${PWD}/log.setFields ] && rm ${PWD}/log.setFields
setFields > log.setFields

[ -f ${PWD}/log.decomposePar ] && rm ${PWD}/log.decomposePar
decomposePar > log.decomposePar

[ -f ${PWD}/log.FGMFoam ] && rm ${PWD}/log.FGMFoam
mpirun -n $nProcs FGMFoam -parallel > log.FGMFoam
    
grep 'ExecutionTime' log.FGMFoam | tail -1 | cut -d "C" -f 1
 
[ -f ${PWD}/log.reconstructPar ] && rm ${PWD}/log.reconstructPar
reconstructPar > log.reconstructPar
rm -rf processor*

exit 0

#-----------------------------------------------------------------------------
